# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('function_name', models.CharField(max_length=100)),
                ('feature_name', models.CharField(max_length=50)),
                ('selection_name', models.CharField(max_length=200)),
                ('choice_type', models.CharField(max_length=15)),
                ('option_min', models.IntegerField()),
                ('option_max', models.IntegerField()),
                ('processed', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='dependent',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Feature'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Feature'),
        ),
    ]
