# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='choice_type',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='feature',
            name='function_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='feature',
            name='group_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='feature',
            name='option_max',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='option_min',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='selection_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
