# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20180430_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='option_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='option_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='processed',
            field=models.NullBooleanField(),
        ),
    ]
