# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_auto_20180501_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Feature'),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Feature'),
        ),
    ]
