# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_auto_20180501_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependency',
            old_name='feature',
            new_name='f1',
        ),
        migrations.RenameField(
            model_name='dependent',
            old_name='feature',
            new_name='f2',
        ),
    ]
