# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_auto_20180501_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependency',
            old_name='f1',
            new_name='feature',
        ),
        migrations.RenameField(
            model_name='dependency',
            old_name='dependency_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='dependent',
            old_name='f2',
            new_name='feature',
        ),
        migrations.RenameField(
            model_name='dependent',
            old_name='dependent_name',
            new_name='name',
        ),
    ]
