# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_auto_20180502_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='name',
            field=models.CharField(blank=True, max_length=51),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='name',
            field=models.CharField(blank=True, max_length=51),
        ),
    ]
