# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_auto_20180504_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='processed',
            new_name='enabled',
        ),
        migrations.AddField(
            model_name='feature',
            name='selected',
            field=models.NullBooleanField(default=False),
        ),
    ]
