# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('selection_name', models.CharField(blank=True, max_length=100)),
                ('rule_type', models.CharField(blank=True, choices=[('CHO', 'choice'), ('SEL', 'selection')], max_length=15)),
                ('option_min', models.IntegerField(blank=True, null=True)),
                ('option_max', models.IntegerField(blank=True, null=True)),
                ('enabled', models.NullBooleanField(default=False)),
                ('selected', models.NullBooleanField(default=False)),
                ('dependency', models.ManyToManyField(related_name='dependent', to='feature2.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
