# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='function',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='feature2.Function'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='function',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='feature2.Group'),
            preserve_default=False,
        ),
    ]
