# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature2', '0002_auto_20180508_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='feature',
            name='dependency',
        ),
        migrations.AddField(
            model_name='dependency',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature2.Feature'),
        ),
    ]
